// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.messages.proto

package msg

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// MessageSend
// @Function
// @Returns:     MessagesSent
type MessagesSend struct {
	RandomID int64      `protobuf:"varint,1,req,name=RandomID" json:"RandomID"`
	Peer     *InputPeer `protobuf:"bytes,2,req,name=Peer" json:"Peer,omitempty"`
	Body     string     `protobuf:"bytes,5,req,name=Body" json:"Body"`
	ReplyTo  int64      `protobuf:"varint,6,opt,name=ReplyTo" json:"ReplyTo"`
}

func (m *MessagesSend) Reset()         { *m = MessagesSend{} }
func (m *MessagesSend) String() string { return proto.CompactTextString(m) }
func (*MessagesSend) ProtoMessage()    {}
func (*MessagesSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{0}
}
func (m *MessagesSend) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesSend.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesSend.Merge(dst, src)
}
func (m *MessagesSend) XXX_Size() int {
	return m.Size()
}
func (m *MessagesSend) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesSend.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesSend proto.InternalMessageInfo

func (m *MessagesSend) GetRandomID() int64 {
	if m != nil {
		return m.RandomID
	}
	return 0
}

func (m *MessagesSend) GetPeer() *InputPeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *MessagesSend) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *MessagesSend) GetReplyTo() int64 {
	if m != nil {
		return m.ReplyTo
	}
	return 0
}

// MessagesEdit
// @Function
// @Returns:    Bool
type MessagesEdit struct {
	RandomID  int64      `protobuf:"varint,1,req,name=RandomID" json:"RandomID"`
	Peer      *InputPeer `protobuf:"bytes,2,req,name=Peer" json:"Peer,omitempty"`
	Body      string     `protobuf:"bytes,3,req,name=Body" json:"Body"`
	MessageID int64      `protobuf:"varint,4,req,name=MessageID" json:"MessageID"`
}

func (m *MessagesEdit) Reset()         { *m = MessagesEdit{} }
func (m *MessagesEdit) String() string { return proto.CompactTextString(m) }
func (*MessagesEdit) ProtoMessage()    {}
func (*MessagesEdit) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{1}
}
func (m *MessagesEdit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesEdit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesEdit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesEdit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesEdit.Merge(dst, src)
}
func (m *MessagesEdit) XXX_Size() int {
	return m.Size()
}
func (m *MessagesEdit) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesEdit.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesEdit proto.InternalMessageInfo

func (m *MessagesEdit) GetRandomID() int64 {
	if m != nil {
		return m.RandomID
	}
	return 0
}

func (m *MessagesEdit) GetPeer() *InputPeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *MessagesEdit) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *MessagesEdit) GetMessageID() int64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

// MessageSendMedia
// @Function
// @Returns:    Messages
type MessagesSendMedia struct {
	RandomID int64      `protobuf:"varint,1,req,name=RandomID" json:"RandomID"`
	Peer     *InputPeer `protobuf:"bytes,2,req,name=Peer" json:"Peer,omitempty"`
	File     *InputFile `protobuf:"bytes,3,req,name=File" json:"File,omitempty"`
}

func (m *MessagesSendMedia) Reset()         { *m = MessagesSendMedia{} }
func (m *MessagesSendMedia) String() string { return proto.CompactTextString(m) }
func (*MessagesSendMedia) ProtoMessage()    {}
func (*MessagesSendMedia) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{2}
}
func (m *MessagesSendMedia) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesSendMedia) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesSendMedia.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesSendMedia) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesSendMedia.Merge(dst, src)
}
func (m *MessagesSendMedia) XXX_Size() int {
	return m.Size()
}
func (m *MessagesSendMedia) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesSendMedia.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesSendMedia proto.InternalMessageInfo

func (m *MessagesSendMedia) GetRandomID() int64 {
	if m != nil {
		return m.RandomID
	}
	return 0
}

func (m *MessagesSendMedia) GetPeer() *InputPeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *MessagesSendMedia) GetFile() *InputFile {
	if m != nil {
		return m.File
	}
	return nil
}

// MessageReadHistory
// @Function
// Returns:
type MessagesReadHistory struct {
	Peer  *InputPeer `protobuf:"bytes,2,req,name=Peer" json:"Peer,omitempty"`
	MaxID int64      `protobuf:"varint,3,req,name=MaxID" json:"MaxID"`
}

func (m *MessagesReadHistory) Reset()         { *m = MessagesReadHistory{} }
func (m *MessagesReadHistory) String() string { return proto.CompactTextString(m) }
func (*MessagesReadHistory) ProtoMessage()    {}
func (*MessagesReadHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{3}
}
func (m *MessagesReadHistory) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesReadHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesReadHistory.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesReadHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesReadHistory.Merge(dst, src)
}
func (m *MessagesReadHistory) XXX_Size() int {
	return m.Size()
}
func (m *MessagesReadHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesReadHistory.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesReadHistory proto.InternalMessageInfo

func (m *MessagesReadHistory) GetPeer() *InputPeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *MessagesReadHistory) GetMaxID() int64 {
	if m != nil {
		return m.MaxID
	}
	return 0
}

// MessagesGet
// @Function
// Returns:     MessagesMany
type MessagesGet struct {
	Peer        *InputPeer `protobuf:"bytes,1,req,name=Peer" json:"Peer,omitempty"`
	MessagesIDs []int64    `protobuf:"varint,2,rep,name=MessagesIDs" json:"MessagesIDs,omitempty"`
}

func (m *MessagesGet) Reset()         { *m = MessagesGet{} }
func (m *MessagesGet) String() string { return proto.CompactTextString(m) }
func (*MessagesGet) ProtoMessage()    {}
func (*MessagesGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{4}
}
func (m *MessagesGet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesGet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesGet.Merge(dst, src)
}
func (m *MessagesGet) XXX_Size() int {
	return m.Size()
}
func (m *MessagesGet) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesGet.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesGet proto.InternalMessageInfo

func (m *MessagesGet) GetPeer() *InputPeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *MessagesGet) GetMessagesIDs() []int64 {
	if m != nil {
		return m.MessagesIDs
	}
	return nil
}

// MessagesGetHistory
// @Function
// Returns:     MessagesMany
type MessagesGetHistory struct {
	Peer  *InputPeer `protobuf:"bytes,2,req,name=Peer" json:"Peer,omitempty"`
	Limit int32      `protobuf:"varint,3,req,name=Limit" json:"Limit"`
	MaxID int64      `protobuf:"varint,4,req,name=MaxID" json:"MaxID"`
	MinID int64      `protobuf:"varint,5,req,name=MinID" json:"MinID"`
}

func (m *MessagesGetHistory) Reset()         { *m = MessagesGetHistory{} }
func (m *MessagesGetHistory) String() string { return proto.CompactTextString(m) }
func (*MessagesGetHistory) ProtoMessage()    {}
func (*MessagesGetHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{5}
}
func (m *MessagesGetHistory) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesGetHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesGetHistory.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesGetHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesGetHistory.Merge(dst, src)
}
func (m *MessagesGetHistory) XXX_Size() int {
	return m.Size()
}
func (m *MessagesGetHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesGetHistory.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesGetHistory proto.InternalMessageInfo

func (m *MessagesGetHistory) GetPeer() *InputPeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *MessagesGetHistory) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *MessagesGetHistory) GetMaxID() int64 {
	if m != nil {
		return m.MaxID
	}
	return 0
}

func (m *MessagesGetHistory) GetMinID() int64 {
	if m != nil {
		return m.MinID
	}
	return 0
}

// MessagesGetDialogs
// @Function
// Returns:     MessagesDialogs
type MessagesGetDialogs struct {
	Limit  int32 `protobuf:"varint,2,req,name=Limit" json:"Limit"`
	Offset int32 `protobuf:"varint,3,req,name=Offset" json:"Offset"`
}

func (m *MessagesGetDialogs) Reset()         { *m = MessagesGetDialogs{} }
func (m *MessagesGetDialogs) String() string { return proto.CompactTextString(m) }
func (*MessagesGetDialogs) ProtoMessage()    {}
func (*MessagesGetDialogs) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{6}
}
func (m *MessagesGetDialogs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesGetDialogs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesGetDialogs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesGetDialogs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesGetDialogs.Merge(dst, src)
}
func (m *MessagesGetDialogs) XXX_Size() int {
	return m.Size()
}
func (m *MessagesGetDialogs) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesGetDialogs.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesGetDialogs proto.InternalMessageInfo

func (m *MessagesGetDialogs) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *MessagesGetDialogs) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

// MessagesGetDialog
// @Function
// Returns: Dialog
type MessagesGetDialog struct {
	Peer *InputPeer `protobuf:"bytes,1,req,name=Peer" json:"Peer,omitempty"`
}

func (m *MessagesGetDialog) Reset()         { *m = MessagesGetDialog{} }
func (m *MessagesGetDialog) String() string { return proto.CompactTextString(m) }
func (*MessagesGetDialog) ProtoMessage()    {}
func (*MessagesGetDialog) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{7}
}
func (m *MessagesGetDialog) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesGetDialog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesGetDialog.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesGetDialog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesGetDialog.Merge(dst, src)
}
func (m *MessagesGetDialog) XXX_Size() int {
	return m.Size()
}
func (m *MessagesGetDialog) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesGetDialog.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesGetDialog proto.InternalMessageInfo

func (m *MessagesGetDialog) GetPeer() *InputPeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

// MessagesSetTyping
// @Function
// Returns: Bool
type MessagesSetTyping struct {
	Peer   *InputPeer   `protobuf:"bytes,1,req,name=Peer" json:"Peer,omitempty"`
	Action TypingAction `protobuf:"varint,2,req,name=Action,enum=msg.TypingAction" json:"Action"`
}

func (m *MessagesSetTyping) Reset()         { *m = MessagesSetTyping{} }
func (m *MessagesSetTyping) String() string { return proto.CompactTextString(m) }
func (*MessagesSetTyping) ProtoMessage()    {}
func (*MessagesSetTyping) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{8}
}
func (m *MessagesSetTyping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesSetTyping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesSetTyping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesSetTyping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesSetTyping.Merge(dst, src)
}
func (m *MessagesSetTyping) XXX_Size() int {
	return m.Size()
}
func (m *MessagesSetTyping) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesSetTyping.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesSetTyping proto.InternalMessageInfo

func (m *MessagesSetTyping) GetPeer() *InputPeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *MessagesSetTyping) GetAction() TypingAction {
	if m != nil {
		return m.Action
	}
	return TypingAction_Typing
}

// MessagesCreateGroup
// @Function
// @Returns: Bool
type MessagesCreateGroup struct {
	Users []*InputUser `protobuf:"bytes,1,rep,name=Users" json:"Users,omitempty"`
	Title string       `protobuf:"bytes,2,req,name=Title" json:"Title"`
}

func (m *MessagesCreateGroup) Reset()         { *m = MessagesCreateGroup{} }
func (m *MessagesCreateGroup) String() string { return proto.CompactTextString(m) }
func (*MessagesCreateGroup) ProtoMessage()    {}
func (*MessagesCreateGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{9}
}
func (m *MessagesCreateGroup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesCreateGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesCreateGroup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesCreateGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesCreateGroup.Merge(dst, src)
}
func (m *MessagesCreateGroup) XXX_Size() int {
	return m.Size()
}
func (m *MessagesCreateGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesCreateGroup.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesCreateGroup proto.InternalMessageInfo

func (m *MessagesCreateGroup) GetUsers() []*InputUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *MessagesCreateGroup) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// MessagesAddGroupUser
// @Function
// @Returns: Bool
type MessagesAddGroupUser struct {
	ChatID       int64      `protobuf:"varint,1,req,name=ChatID" json:"ChatID"`
	User         *InputUser `protobuf:"bytes,2,req,name=User" json:"User,omitempty"`
	ForwardLimit int32      `protobuf:"varint,3,req,name=ForwardLimit" json:"ForwardLimit"`
}

func (m *MessagesAddGroupUser) Reset()         { *m = MessagesAddGroupUser{} }
func (m *MessagesAddGroupUser) String() string { return proto.CompactTextString(m) }
func (*MessagesAddGroupUser) ProtoMessage()    {}
func (*MessagesAddGroupUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{10}
}
func (m *MessagesAddGroupUser) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesAddGroupUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesAddGroupUser.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesAddGroupUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesAddGroupUser.Merge(dst, src)
}
func (m *MessagesAddGroupUser) XXX_Size() int {
	return m.Size()
}
func (m *MessagesAddGroupUser) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesAddGroupUser.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesAddGroupUser proto.InternalMessageInfo

func (m *MessagesAddGroupUser) GetChatID() int64 {
	if m != nil {
		return m.ChatID
	}
	return 0
}

func (m *MessagesAddGroupUser) GetUser() *InputUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *MessagesAddGroupUser) GetForwardLimit() int32 {
	if m != nil {
		return m.ForwardLimit
	}
	return 0
}

// MessagesEditGroupTitle
// @Function
// @Returns: Bool
type MessagesEditGroupTitle struct {
	ChatID int64  `protobuf:"varint,1,req,name=ChatID" json:"ChatID"`
	Title  string `protobuf:"bytes,2,req,name=Title" json:"Title"`
}

func (m *MessagesEditGroupTitle) Reset()         { *m = MessagesEditGroupTitle{} }
func (m *MessagesEditGroupTitle) String() string { return proto.CompactTextString(m) }
func (*MessagesEditGroupTitle) ProtoMessage()    {}
func (*MessagesEditGroupTitle) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{11}
}
func (m *MessagesEditGroupTitle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesEditGroupTitle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesEditGroupTitle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesEditGroupTitle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesEditGroupTitle.Merge(dst, src)
}
func (m *MessagesEditGroupTitle) XXX_Size() int {
	return m.Size()
}
func (m *MessagesEditGroupTitle) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesEditGroupTitle.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesEditGroupTitle proto.InternalMessageInfo

func (m *MessagesEditGroupTitle) GetChatID() int64 {
	if m != nil {
		return m.ChatID
	}
	return 0
}

func (m *MessagesEditGroupTitle) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// MessagesDeleteGroupUser
// @Function
// @Returns: Bool
type MessagesDeleteGroupUser struct {
	ChatID int64      `protobuf:"varint,1,req,name=ChatID" json:"ChatID"`
	User   *InputUser `protobuf:"bytes,2,req,name=User" json:"User,omitempty"`
}

func (m *MessagesDeleteGroupUser) Reset()         { *m = MessagesDeleteGroupUser{} }
func (m *MessagesDeleteGroupUser) String() string { return proto.CompactTextString(m) }
func (*MessagesDeleteGroupUser) ProtoMessage()    {}
func (*MessagesDeleteGroupUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{12}
}
func (m *MessagesDeleteGroupUser) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesDeleteGroupUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesDeleteGroupUser.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesDeleteGroupUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesDeleteGroupUser.Merge(dst, src)
}
func (m *MessagesDeleteGroupUser) XXX_Size() int {
	return m.Size()
}
func (m *MessagesDeleteGroupUser) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesDeleteGroupUser.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesDeleteGroupUser proto.InternalMessageInfo

func (m *MessagesDeleteGroupUser) GetChatID() int64 {
	if m != nil {
		return m.ChatID
	}
	return 0
}

func (m *MessagesDeleteGroupUser) GetUser() *InputUser {
	if m != nil {
		return m.User
	}
	return nil
}

// MessagesDialogs
type MessagesDialogs struct {
	Dialogs  []*Dialog      `protobuf:"bytes,1,rep,name=Dialogs" json:"Dialogs,omitempty"`
	Users    []*User        `protobuf:"bytes,2,rep,name=Users" json:"Users,omitempty"`
	Messages []*UserMessage `protobuf:"bytes,3,rep,name=Messages" json:"Messages,omitempty"`
	Count    int32          `protobuf:"varint,4,req,name=Count" json:"Count"`
	UpdateID int64          `protobuf:"varint,5,req,name=UpdateID" json:"UpdateID"`
}

func (m *MessagesDialogs) Reset()         { *m = MessagesDialogs{} }
func (m *MessagesDialogs) String() string { return proto.CompactTextString(m) }
func (*MessagesDialogs) ProtoMessage()    {}
func (*MessagesDialogs) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{13}
}
func (m *MessagesDialogs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesDialogs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesDialogs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesDialogs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesDialogs.Merge(dst, src)
}
func (m *MessagesDialogs) XXX_Size() int {
	return m.Size()
}
func (m *MessagesDialogs) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesDialogs.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesDialogs proto.InternalMessageInfo

func (m *MessagesDialogs) GetDialogs() []*Dialog {
	if m != nil {
		return m.Dialogs
	}
	return nil
}

func (m *MessagesDialogs) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *MessagesDialogs) GetMessages() []*UserMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *MessagesDialogs) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MessagesDialogs) GetUpdateID() int64 {
	if m != nil {
		return m.UpdateID
	}
	return 0
}

// MessagesSent
type MessagesSent struct {
	MessageID int64 `protobuf:"varint,1,req,name=MessageID" json:"MessageID"`
	RandomID  int64 `protobuf:"varint,2,req,name=RandomID" json:"RandomID"`
	CreatedOn int64 `protobuf:"varint,3,req,name=CreatedOn" json:"CreatedOn"`
}

func (m *MessagesSent) Reset()         { *m = MessagesSent{} }
func (m *MessagesSent) String() string { return proto.CompactTextString(m) }
func (*MessagesSent) ProtoMessage()    {}
func (*MessagesSent) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{14}
}
func (m *MessagesSent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesSent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesSent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesSent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesSent.Merge(dst, src)
}
func (m *MessagesSent) XXX_Size() int {
	return m.Size()
}
func (m *MessagesSent) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesSent.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesSent proto.InternalMessageInfo

func (m *MessagesSent) GetMessageID() int64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

func (m *MessagesSent) GetRandomID() int64 {
	if m != nil {
		return m.RandomID
	}
	return 0
}

func (m *MessagesSent) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

// MessagesMany
type MessagesMany struct {
	Messages []*UserMessage `protobuf:"bytes,1,rep,name=Messages" json:"Messages,omitempty"`
	Users    []*User        `protobuf:"bytes,2,rep,name=Users" json:"Users,omitempty"`
}

func (m *MessagesMany) Reset()         { *m = MessagesMany{} }
func (m *MessagesMany) String() string { return proto.CompactTextString(m) }
func (*MessagesMany) ProtoMessage()    {}
func (*MessagesMany) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_messages_dbf9971ce524e0d8, []int{15}
}
func (m *MessagesMany) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessagesMany) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessagesMany.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MessagesMany) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesMany.Merge(dst, src)
}
func (m *MessagesMany) XXX_Size() int {
	return m.Size()
}
func (m *MessagesMany) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesMany.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesMany proto.InternalMessageInfo

func (m *MessagesMany) GetMessages() []*UserMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *MessagesMany) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*MessagesSend)(nil), "msg.MessagesSend")
	proto.RegisterType((*MessagesEdit)(nil), "msg.MessagesEdit")
	proto.RegisterType((*MessagesSendMedia)(nil), "msg.MessagesSendMedia")
	proto.RegisterType((*MessagesReadHistory)(nil), "msg.MessagesReadHistory")
	proto.RegisterType((*MessagesGet)(nil), "msg.MessagesGet")
	proto.RegisterType((*MessagesGetHistory)(nil), "msg.MessagesGetHistory")
	proto.RegisterType((*MessagesGetDialogs)(nil), "msg.MessagesGetDialogs")
	proto.RegisterType((*MessagesGetDialog)(nil), "msg.MessagesGetDialog")
	proto.RegisterType((*MessagesSetTyping)(nil), "msg.MessagesSetTyping")
	proto.RegisterType((*MessagesCreateGroup)(nil), "msg.MessagesCreateGroup")
	proto.RegisterType((*MessagesAddGroupUser)(nil), "msg.MessagesAddGroupUser")
	proto.RegisterType((*MessagesEditGroupTitle)(nil), "msg.MessagesEditGroupTitle")
	proto.RegisterType((*MessagesDeleteGroupUser)(nil), "msg.MessagesDeleteGroupUser")
	proto.RegisterType((*MessagesDialogs)(nil), "msg.MessagesDialogs")
	proto.RegisterType((*MessagesSent)(nil), "msg.MessagesSent")
	proto.RegisterType((*MessagesMany)(nil), "msg.MessagesMany")
}
func (m *MessagesSend) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesSend) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.RandomID))
	if m.Peer == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintApiMessages(dAtA, i, uint64(m.Peer.Size()))
		n1, err := m.Peer.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	dAtA[i] = 0x2a
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(len(m.Body)))
	i += copy(dAtA[i:], m.Body)
	dAtA[i] = 0x30
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.ReplyTo))
	return i, nil
}

func (m *MessagesEdit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesEdit) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.RandomID))
	if m.Peer == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintApiMessages(dAtA, i, uint64(m.Peer.Size()))
		n2, err := m.Peer.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	dAtA[i] = 0x1a
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(len(m.Body)))
	i += copy(dAtA[i:], m.Body)
	dAtA[i] = 0x20
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.MessageID))
	return i, nil
}

func (m *MessagesSendMedia) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesSendMedia) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.RandomID))
	if m.Peer == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintApiMessages(dAtA, i, uint64(m.Peer.Size()))
		n3, err := m.Peer.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.File == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("File")
	} else {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintApiMessages(dAtA, i, uint64(m.File.Size()))
		n4, err := m.File.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	return i, nil
}

func (m *MessagesReadHistory) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesReadHistory) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Peer == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintApiMessages(dAtA, i, uint64(m.Peer.Size()))
		n5, err := m.Peer.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	dAtA[i] = 0x18
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.MaxID))
	return i, nil
}

func (m *MessagesGet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesGet) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Peer == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	} else {
		dAtA[i] = 0xa
		i++
		i = encodeVarintApiMessages(dAtA, i, uint64(m.Peer.Size()))
		n6, err := m.Peer.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if len(m.MessagesIDs) > 0 {
		for _, num := range m.MessagesIDs {
			dAtA[i] = 0x10
			i++
			i = encodeVarintApiMessages(dAtA, i, uint64(num))
		}
	}
	return i, nil
}

func (m *MessagesGetHistory) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesGetHistory) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Peer == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintApiMessages(dAtA, i, uint64(m.Peer.Size()))
		n7, err := m.Peer.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	dAtA[i] = 0x18
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.Limit))
	dAtA[i] = 0x20
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.MaxID))
	dAtA[i] = 0x28
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.MinID))
	return i, nil
}

func (m *MessagesGetDialogs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesGetDialogs) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x10
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.Limit))
	dAtA[i] = 0x18
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.Offset))
	return i, nil
}

func (m *MessagesGetDialog) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesGetDialog) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Peer == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	} else {
		dAtA[i] = 0xa
		i++
		i = encodeVarintApiMessages(dAtA, i, uint64(m.Peer.Size()))
		n8, err := m.Peer.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	return i, nil
}

func (m *MessagesSetTyping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesSetTyping) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Peer == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	} else {
		dAtA[i] = 0xa
		i++
		i = encodeVarintApiMessages(dAtA, i, uint64(m.Peer.Size()))
		n9, err := m.Peer.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n9
	}
	dAtA[i] = 0x10
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.Action))
	return i, nil
}

func (m *MessagesCreateGroup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesCreateGroup) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Users) > 0 {
		for _, msg := range m.Users {
			dAtA[i] = 0xa
			i++
			i = encodeVarintApiMessages(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(len(m.Title)))
	i += copy(dAtA[i:], m.Title)
	return i, nil
}

func (m *MessagesAddGroupUser) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesAddGroupUser) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.ChatID))
	if m.User == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("User")
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintApiMessages(dAtA, i, uint64(m.User.Size()))
		n10, err := m.User.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n10
	}
	dAtA[i] = 0x18
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.ForwardLimit))
	return i, nil
}

func (m *MessagesEditGroupTitle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesEditGroupTitle) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.ChatID))
	dAtA[i] = 0x12
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(len(m.Title)))
	i += copy(dAtA[i:], m.Title)
	return i, nil
}

func (m *MessagesDeleteGroupUser) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesDeleteGroupUser) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.ChatID))
	if m.User == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("User")
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintApiMessages(dAtA, i, uint64(m.User.Size()))
		n11, err := m.User.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n11
	}
	return i, nil
}

func (m *MessagesDialogs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesDialogs) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Dialogs) > 0 {
		for _, msg := range m.Dialogs {
			dAtA[i] = 0xa
			i++
			i = encodeVarintApiMessages(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Users) > 0 {
		for _, msg := range m.Users {
			dAtA[i] = 0x12
			i++
			i = encodeVarintApiMessages(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Messages) > 0 {
		for _, msg := range m.Messages {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintApiMessages(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	dAtA[i] = 0x20
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.Count))
	dAtA[i] = 0x28
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.UpdateID))
	return i, nil
}

func (m *MessagesSent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesSent) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.MessageID))
	dAtA[i] = 0x10
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.RandomID))
	dAtA[i] = 0x18
	i++
	i = encodeVarintApiMessages(dAtA, i, uint64(m.CreatedOn))
	return i, nil
}

func (m *MessagesMany) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessagesMany) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Messages) > 0 {
		for _, msg := range m.Messages {
			dAtA[i] = 0xa
			i++
			i = encodeVarintApiMessages(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Users) > 0 {
		for _, msg := range m.Users {
			dAtA[i] = 0x12
			i++
			i = encodeVarintApiMessages(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func encodeVarintApiMessages(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *MessagesSend) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovApiMessages(uint64(m.RandomID))
	if m.Peer != nil {
		l = m.Peer.Size()
		n += 1 + l + sovApiMessages(uint64(l))
	}
	l = len(m.Body)
	n += 1 + l + sovApiMessages(uint64(l))
	n += 1 + sovApiMessages(uint64(m.ReplyTo))
	return n
}

func (m *MessagesEdit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovApiMessages(uint64(m.RandomID))
	if m.Peer != nil {
		l = m.Peer.Size()
		n += 1 + l + sovApiMessages(uint64(l))
	}
	l = len(m.Body)
	n += 1 + l + sovApiMessages(uint64(l))
	n += 1 + sovApiMessages(uint64(m.MessageID))
	return n
}

func (m *MessagesSendMedia) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovApiMessages(uint64(m.RandomID))
	if m.Peer != nil {
		l = m.Peer.Size()
		n += 1 + l + sovApiMessages(uint64(l))
	}
	if m.File != nil {
		l = m.File.Size()
		n += 1 + l + sovApiMessages(uint64(l))
	}
	return n
}

func (m *MessagesReadHistory) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Peer != nil {
		l = m.Peer.Size()
		n += 1 + l + sovApiMessages(uint64(l))
	}
	n += 1 + sovApiMessages(uint64(m.MaxID))
	return n
}

func (m *MessagesGet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Peer != nil {
		l = m.Peer.Size()
		n += 1 + l + sovApiMessages(uint64(l))
	}
	if len(m.MessagesIDs) > 0 {
		for _, e := range m.MessagesIDs {
			n += 1 + sovApiMessages(uint64(e))
		}
	}
	return n
}

func (m *MessagesGetHistory) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Peer != nil {
		l = m.Peer.Size()
		n += 1 + l + sovApiMessages(uint64(l))
	}
	n += 1 + sovApiMessages(uint64(m.Limit))
	n += 1 + sovApiMessages(uint64(m.MaxID))
	n += 1 + sovApiMessages(uint64(m.MinID))
	return n
}

func (m *MessagesGetDialogs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovApiMessages(uint64(m.Limit))
	n += 1 + sovApiMessages(uint64(m.Offset))
	return n
}

func (m *MessagesGetDialog) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Peer != nil {
		l = m.Peer.Size()
		n += 1 + l + sovApiMessages(uint64(l))
	}
	return n
}

func (m *MessagesSetTyping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Peer != nil {
		l = m.Peer.Size()
		n += 1 + l + sovApiMessages(uint64(l))
	}
	n += 1 + sovApiMessages(uint64(m.Action))
	return n
}

func (m *MessagesCreateGroup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Users) > 0 {
		for _, e := range m.Users {
			l = e.Size()
			n += 1 + l + sovApiMessages(uint64(l))
		}
	}
	l = len(m.Title)
	n += 1 + l + sovApiMessages(uint64(l))
	return n
}

func (m *MessagesAddGroupUser) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovApiMessages(uint64(m.ChatID))
	if m.User != nil {
		l = m.User.Size()
		n += 1 + l + sovApiMessages(uint64(l))
	}
	n += 1 + sovApiMessages(uint64(m.ForwardLimit))
	return n
}

func (m *MessagesEditGroupTitle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovApiMessages(uint64(m.ChatID))
	l = len(m.Title)
	n += 1 + l + sovApiMessages(uint64(l))
	return n
}

func (m *MessagesDeleteGroupUser) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovApiMessages(uint64(m.ChatID))
	if m.User != nil {
		l = m.User.Size()
		n += 1 + l + sovApiMessages(uint64(l))
	}
	return n
}

func (m *MessagesDialogs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Dialogs) > 0 {
		for _, e := range m.Dialogs {
			l = e.Size()
			n += 1 + l + sovApiMessages(uint64(l))
		}
	}
	if len(m.Users) > 0 {
		for _, e := range m.Users {
			l = e.Size()
			n += 1 + l + sovApiMessages(uint64(l))
		}
	}
	if len(m.Messages) > 0 {
		for _, e := range m.Messages {
			l = e.Size()
			n += 1 + l + sovApiMessages(uint64(l))
		}
	}
	n += 1 + sovApiMessages(uint64(m.Count))
	n += 1 + sovApiMessages(uint64(m.UpdateID))
	return n
}

func (m *MessagesSent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovApiMessages(uint64(m.MessageID))
	n += 1 + sovApiMessages(uint64(m.RandomID))
	n += 1 + sovApiMessages(uint64(m.CreatedOn))
	return n
}

func (m *MessagesMany) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Messages) > 0 {
		for _, e := range m.Messages {
			l = e.Size()
			n += 1 + l + sovApiMessages(uint64(l))
		}
	}
	if len(m.Users) > 0 {
		for _, e := range m.Users {
			l = e.Size()
			n += 1 + l + sovApiMessages(uint64(l))
		}
	}
	return n
}

func sovApiMessages(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozApiMessages(x uint64) (n int) {
	return sovApiMessages(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MessagesSend) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesSend: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesSend: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RandomID", wireType)
			}
			m.RandomID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RandomID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peer == nil {
				m.Peer = &InputPeer{}
			}
			if err := m.Peer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Body", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Body = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000004)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplyTo", wireType)
			}
			m.ReplyTo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReplyTo |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("RandomID")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Body")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagesEdit) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesEdit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesEdit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RandomID", wireType)
			}
			m.RandomID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RandomID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peer == nil {
				m.Peer = &InputPeer{}
			}
			if err := m.Peer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Body", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Body = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageID", wireType)
			}
			m.MessageID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000008)
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("RandomID")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Body")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("MessageID")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagesSendMedia) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesSendMedia: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesSendMedia: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RandomID", wireType)
			}
			m.RandomID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RandomID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peer == nil {
				m.Peer = &InputPeer{}
			}
			if err := m.Peer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field File", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.File == nil {
				m.File = &InputFile{}
			}
			if err := m.File.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000004)
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("RandomID")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("File")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagesReadHistory) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesReadHistory: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesReadHistory: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peer == nil {
				m.Peer = &InputPeer{}
			}
			if err := m.Peer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxID", wireType)
			}
			m.MaxID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("MaxID")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagesGet) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesGet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesGet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peer == nil {
				m.Peer = &InputPeer{}
			}
			if err := m.Peer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowApiMessages
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.MessagesIDs = append(m.MessagesIDs, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowApiMessages
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthApiMessages
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.MessagesIDs) == 0 {
					m.MessagesIDs = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowApiMessages
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.MessagesIDs = append(m.MessagesIDs, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field MessagesIDs", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagesGetHistory) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesGetHistory: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesGetHistory: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peer == nil {
				m.Peer = &InputPeer{}
			}
			if err := m.Peer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxID", wireType)
			}
			m.MaxID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000004)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinID", wireType)
			}
			m.MinID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000008)
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Limit")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("MaxID")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("MinID")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagesGetDialogs) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesGetDialogs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesGetDialogs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			m.Offset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Offset |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Limit")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Offset")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagesGetDialog) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesGetDialog: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesGetDialog: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peer == nil {
				m.Peer = &InputPeer{}
			}
			if err := m.Peer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagesSetTyping) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesSetTyping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesSetTyping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peer == nil {
				m.Peer = &InputPeer{}
			}
			if err := m.Peer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Action", wireType)
			}
			m.Action = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Action |= (TypingAction(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Peer")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Action")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagesCreateGroup) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesCreateGroup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesCreateGroup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Users", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Users = append(m.Users, &InputUser{})
			if err := m.Users[len(m.Users)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Title")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagesAddGroupUser) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesAddGroupUser: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesAddGroupUser: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChatID", wireType)
			}
			m.ChatID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChatID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.User == nil {
				m.User = &InputUser{}
			}
			if err := m.User.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForwardLimit", wireType)
			}
			m.ForwardLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ForwardLimit |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000004)
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("ChatID")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("User")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("ForwardLimit")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagesEditGroupTitle) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesEditGroupTitle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesEditGroupTitle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChatID", wireType)
			}
			m.ChatID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChatID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("ChatID")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Title")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagesDeleteGroupUser) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesDeleteGroupUser: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesDeleteGroupUser: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChatID", wireType)
			}
			m.ChatID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChatID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.User == nil {
				m.User = &InputUser{}
			}
			if err := m.User.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("ChatID")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("User")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagesDialogs) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesDialogs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesDialogs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dialogs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dialogs = append(m.Dialogs, &Dialog{})
			if err := m.Dialogs[len(m.Dialogs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Users", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Users = append(m.Users, &User{})
			if err := m.Users[len(m.Users)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Messages", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Messages = append(m.Messages, &UserMessage{})
			if err := m.Messages[len(m.Messages)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateID", wireType)
			}
			m.UpdateID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("Count")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("UpdateID")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagesSent) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesSent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesSent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageID", wireType)
			}
			m.MessageID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RandomID", wireType)
			}
			m.RandomID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RandomID |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedOn", wireType)
			}
			m.CreatedOn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedOn |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000004)
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("MessageID")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("RandomID")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("CreatedOn")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessagesMany) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessagesMany: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessagesMany: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Messages", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Messages = append(m.Messages, &UserMessage{})
			if err := m.Messages[len(m.Messages)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Users", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Users = append(m.Users, &User{})
			if err := m.Users[len(m.Users)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApiMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApiMessages(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApiMessages
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApiMessages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthApiMessages
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowApiMessages
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipApiMessages(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthApiMessages = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApiMessages   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("api.messages.proto", fileDescriptor_api_messages_dbf9971ce524e0d8) }

var fileDescriptor_api_messages_dbf9971ce524e0d8 = []byte{
	// 650 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcf, 0x6b, 0xd4, 0x40,
	0x14, 0xde, 0x49, 0xb2, 0x6d, 0x77, 0x5a, 0x6a, 0x1b, 0x45, 0x43, 0x91, 0x34, 0x0c, 0x0a, 0x7b,
	0x90, 0x15, 0x7a, 0xf1, 0xdc, 0x36, 0xb6, 0x06, 0x5c, 0x2b, 0x69, 0x8b, 0x07, 0xf1, 0x30, 0x34,
	0xd3, 0xed, 0xc0, 0x6e, 0x26, 0x24, 0x53, 0x6c, 0x0e, 0x5e, 0x3c, 0x8b, 0x88, 0xff, 0x93, 0xd0,
	0x63, 0x8f, 0x9e, 0x44, 0x76, 0xff, 0x11, 0xc9, 0x4b, 0x26, 0x3f, 0xba, 0xda, 0x5d, 0x61, 0x6f,
	0xbb, 0xdf, 0xf7, 0xe6, 0x7b, 0xdf, 0x7b, 0xf3, 0xe6, 0x05, 0x9b, 0x34, 0xe2, 0xbd, 0x11, 0x4b,
	0x12, 0x3a, 0x60, 0x49, 0x2f, 0x8a, 0x85, 0x14, 0xa6, 0x3e, 0x4a, 0x06, 0x5b, 0x1b, 0x67, 0x22,
	0x66, 0x3d, 0x99, 0x46, 0x0a, 0x26, 0x5f, 0x11, 0x5e, 0xeb, 0x17, 0x91, 0xc7, 0x2c, 0x0c, 0x4c,
	0x07, 0xaf, 0xf8, 0x34, 0x0c, 0xc4, 0xc8, 0x73, 0x2d, 0xe4, 0x68, 0x5d, 0x7d, 0xcf, 0xb8, 0xfe,
	0xb5, 0xdd, 0xf2, 0x4b, 0xd4, 0x24, 0xd8, 0x78, 0xcb, 0x58, 0x6c, 0x69, 0x8e, 0xd6, 0x5d, 0xdd,
	0x59, 0xef, 0x8d, 0x92, 0x41, 0xcf, 0x0b, 0xa3, 0x4b, 0x99, 0xa1, 0x3e, 0x70, 0xa6, 0x85, 0x8d,
	0x3d, 0x11, 0xa4, 0x56, 0xdb, 0xd1, 0xba, 0x9d, 0x42, 0x01, 0x10, 0xd3, 0xc6, 0xcb, 0x3e, 0x8b,
	0x86, 0xe9, 0x89, 0xb0, 0x96, 0x1c, 0x54, 0xca, 0x2b, 0x90, 0x7c, 0xaf, 0x19, 0x7a, 0x19, 0x70,
	0xb9, 0x60, 0x43, 0xfa, 0x94, 0x21, 0x82, 0x3b, 0x45, 0x3e, 0xcf, 0xb5, 0x8c, 0x5a, 0x82, 0x0a,
	0x26, 0x9f, 0xf0, 0x66, 0xbd, 0x49, 0x7d, 0x16, 0x70, 0xba, 0x20, 0x63, 0x04, 0x1b, 0x07, 0x7c,
	0xc8, 0xc0, 0x58, 0x23, 0x26, 0x43, 0x7d, 0xe0, 0xc8, 0x29, 0xbe, 0xaf, 0xd2, 0xfb, 0x8c, 0x06,
	0xaf, 0x78, 0x22, 0x45, 0x9c, 0xce, 0x25, 0xbf, 0x85, 0xdb, 0x7d, 0x7a, 0xe5, 0xb9, 0xa0, 0xaf,
	0x1c, 0xe6, 0x10, 0x39, 0xc6, 0xab, 0x4a, 0xf6, 0x90, 0xc9, 0x52, 0x0e, 0xdd, 0x21, 0xe7, 0x54,
	0x47, 0x3c, 0x37, 0xb1, 0x34, 0x47, 0xef, 0xea, 0x7e, 0x1d, 0x22, 0x5f, 0x10, 0x36, 0x6b, 0xaa,
	0xff, 0xe9, 0xf5, 0x35, 0x1f, 0x71, 0x09, 0x5e, 0xdb, 0xca, 0x2b, 0x40, 0x55, 0x1d, 0xc6, 0x54,
	0x1d, 0xc0, 0xf1, 0xd0, 0x73, 0x61, 0xda, 0x2a, 0x2e, 0x83, 0xc8, 0x9b, 0x86, 0x1b, 0x97, 0xd3,
	0xa1, 0x18, 0x24, 0x55, 0x26, 0x6d, 0x3a, 0xd3, 0x63, 0xbc, 0x74, 0x74, 0x7e, 0x9e, 0xb0, 0xa6,
	0x8d, 0x02, 0x23, 0x2f, 0xaa, 0x49, 0x28, 0xf5, 0xe6, 0xe9, 0x1c, 0xb9, 0xa8, 0x8f, 0x90, 0x3c,
	0x49, 0x23, 0x1e, 0xce, 0x75, 0xd0, 0x7c, 0x8e, 0x97, 0x76, 0xcf, 0x24, 0x17, 0x21, 0x98, 0x5d,
	0xdf, 0xd9, 0x84, 0xa8, 0x5c, 0x20, 0x27, 0x94, 0xc5, 0xfc, 0x1f, 0x79, 0x57, 0x4d, 0xcb, 0x7e,
	0xcc, 0xa8, 0x64, 0x87, 0xb1, 0xb8, 0x8c, 0xcc, 0x27, 0xb8, 0x7d, 0x9a, 0xb0, 0x38, 0xb1, 0x90,
	0xa3, 0x37, 0x93, 0x65, 0xb0, 0x9f, 0x93, 0x59, 0x67, 0x4e, 0xb8, 0x1c, 0x32, 0x48, 0xa6, 0x1e,
	0x4a, 0x0e, 0x91, 0xcf, 0x08, 0x3f, 0x50, 0xca, 0xbb, 0x41, 0x00, 0xb2, 0xd9, 0xa9, 0xac, 0x65,
	0xfb, 0x17, 0x54, 0xde, 0x7a, 0x07, 0x05, 0x96, 0x15, 0x99, 0x45, 0x4d, 0x5f, 0x3d, 0xe4, 0x05,
	0xce, 0xec, 0xe2, 0xb5, 0x03, 0x11, 0x7f, 0xa4, 0x71, 0x30, 0x3d, 0x01, 0x0d, 0x86, 0xf8, 0xf8,
	0x61, 0x7d, 0x3d, 0x80, 0x09, 0xb0, 0x37, 0xc3, 0xc5, 0x5d, 0x85, 0xbd, 0xc7, 0x8f, 0x94, 0xa6,
	0xcb, 0x86, 0xac, 0xe8, 0xd8, 0x62, 0x4a, 0x23, 0x3f, 0x10, 0xbe, 0x57, 0xaa, 0x17, 0xf3, 0xf7,
	0x14, 0x2f, 0x17, 0x3f, 0x8b, 0xdb, 0x58, 0x85, 0xa3, 0x39, 0xe6, 0x2b, 0xce, 0xdc, 0x56, 0x57,
	0xa6, 0x41, 0x50, 0x07, 0x82, 0xea, 0xb7, 0xf5, 0x0c, 0xaf, 0x28, 0x69, 0x4b, 0x87, 0x98, 0x8d,
	0x32, 0xa6, 0x20, 0xfc, 0x32, 0x22, 0x6b, 0xc1, 0xbe, 0xb8, 0x0c, 0x25, 0xbc, 0xa1, 0x72, 0xea,
	0x01, 0xca, 0x96, 0xd9, 0x69, 0x14, 0x50, 0xc9, 0x6e, 0x3d, 0xa3, 0x12, 0x25, 0x57, 0x8d, 0x0f,
	0x85, 0x6c, 0xee, 0x4d, 0xf4, 0xd7, 0xbd, 0xd9, 0x58, 0x91, 0xda, 0x3f, 0x56, 0x64, 0x27, 0x1f,
	0xd2, 0xe0, 0x28, 0x6c, 0xec, 0xa8, 0x0a, 0x26, 0x1f, 0xaa, 0xcc, 0x7d, 0x1a, 0xa6, 0x8d, 0xaa,
	0xd1, 0xcc, 0xaa, 0x67, 0x35, 0x71, 0xcf, 0xba, 0x1e, 0xdb, 0xe8, 0x66, 0x6c, 0xa3, 0xdf, 0x63,
	0x1b, 0x7d, 0x9b, 0xd8, 0xad, 0x9b, 0x89, 0xdd, 0xfa, 0x39, 0xb1, 0x5b, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x72, 0x0b, 0x9f, 0x8f, 0x48, 0x07, 0x00, 0x00,
}
