// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-07-25 15:33:02.098105 +0430 +0430 m=+0.032254097
package domain

var (
	GitVersion = "8836f087c1428f9f3641150212de9e1393a88fff"
	SDKVersion = "v1.0.0"
)
