
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2019-12-28 16:53:22.462646 +0330 +0330 m=+0.098881329
package domain

var (
	GitVersion = "bf729133c80312276872c7bf50589faa72db2109"
	SDKVersion = "v0.9.4"
)
