
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-07-14 11:45:23.549801 +0430 +0430 m=+0.027199589
package domain

var (
	GitVersion = "7b3a2ff18f252b86875baea2e5f1507510e6c697"
	SDKVersion = "v0.11.0"
)
