package config

const (
	ENV_BOUNDLE_ID  = "CFG_BOUNDLE_ID"
	ENV_INSTANCE_ID = "CFG_INSTANCE_ID"
	ENV_NATS_URL    = "CFG_NATS_URL"
	ENV_START_PHONE = "CFG_START_PHONE"
	ENV_END_PHONE   = "CFG_END_PHONE"
)

const (
	SUBJECT_START         = "SUBJECT_START"
	SUBJECT_STOP          = "SUBJECT_STOP"
	SUBJECT_TICKER        = "SUBJECT_TICKER"
	SUBJECT_CREATEAUTHKEY = "SUBJECT_CREATEAUTHKEY"
	SUBJECT_RIGISTER      = "SUBJECT_RIGISTER"
	SUBJECT_LOGIN         = "SUBJECT_LOGIN"
)
