{
 "title": "Supernumerary",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Network Usage / 10 s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "increase(cnt_send[10s])", "legendFormat": "Send/Upload Byte" },
    { "expr": "increase(cnt_receive[10s])", "legendFormat": "Receive /Download Byte" }
   ]
  },
  {
   "title": "Active Actors",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(gauge_actor)", "legendFormat": "Active Connections" }
   ]
  },
  { "title": "Vector Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Response/Updates Conts  / 5 min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cnt_response_count[5m])",
     "legendFormat": "{{ fn }}"
    }
   ]
  },
  {
   "title": "Request Counts / 5 min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cnt_request_count[5m])",
     "legendFormat": "{{ fn }}"
    }
   ]
  },
  {
   "title": "Timedout Requests / 5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cnt_timeout_count[5m])",
     "legendFormat": "{{ fn }}"
    }
   ]
  },
  {
   "title": "Success Requests /5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cnt_succeess_count[5m])",
     "legendFormat": "{{ fn }}"
    }
   ]
  },
  {
   "title": "Differed Response / 5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cnt_differed_count[5m])",
     "legendFormat": "{{ fn }}"
    }
   ]
  },
  {
   "title": "Scenario Counters / 5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(cnt_failed_scenario_count[5m])",
     "legendFormat": "Failed Scenario"
    },
    {
     "expr": "increase(cnt_succeed_scenario_count[5m])",
     "legendFormat": "Succeed Scenario"
    }
   ]
  },
  {
   "title": "Error Counters / 5 min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "increase(cnt_error_count[5m])", "legendFormat": "Error" },
    {
     "expr": "increase(cnt_disconnect_count[5m])",
     "legendFormat": "Disconnect"
    },
    {
     "expr": "increase(cnt_file_error_count[5m])",
     "legendFormat": "File Error"
    }
   ]
  },
  { "title": "Histograms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "File Upload Latency / 5 min",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(hist_file_latency_bucket[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Success Latency / 5 min",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(hist_success_latency_bucket[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Timeout Latency / 5 min",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(increase(hist_timeout_latency_bucket[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Differed Response Latency / 5 min",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum(increase(hist_differed_latency_bucket[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}