[package]
name = "rust-helpers"
version = "0.1.0"
authors = ["Ehsan N. Moosa <ehsan.code@nested.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primes = "0.2.4"
sha2 = "0.8.0"
aes-gcm = "0.3.0"
aead = "0.2.0"