version: '2'
services:

## Supernumerary SERVICE 001
  supernumerary-001:
    image: registry.ronaksoftware.com/ronak/riversdk/supernumerary:0.1
    restart: always
    expose:
      - 2374
    volumes:
      - ./_cache:/ronak/_cache
    environment:
      - CFG_BUNDLE_ID=001
      - CFG_NATS_URL=nats://nats-super:4222
      - CFG_CACHE_REDIS_PERM_DSN=redis-super:6379
      - CFG_CACHE_REDIS_PERM_PASS=ehsan2374
    networks:
      - river
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    depends_on:
      - nats

## NATS SERVICE        
  nats-super:
    image: registry.ronaksoftware.com/base/nats
    restart: always
    ports:
      - 4222:4222
      - 8222:8222
    networks:
      - river

## REDIS SERVICE
  redis-super:
    restart: on-failure
    image: registry.ronaksoftware.com/base/redis
    command: redis-server --requirepass ehsan2374 --save 1 1
    volumes:
      - ./_redis:/data:rw
    ports:
      - 6379:6379
    networks:
      - river

networks:
  river:
    external:
      name: river
