{
 "title": "Supernumerary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rate(cnt_send[10s])", "legendFormat": "Send/Upload Byte" },
    { "expr": "rate(cnt_receive[10s])", "legendFormat": "Receive /Download Byte" }
   ]
  },
  {
   "title": "Active Actors",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gauge_actor", "legendFormat": "Active Connections" }
   ]
  },
  { "title": "Vector Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Response/Updates Conts / h",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cnt_response_count[1h])",
     "legendFormat": "{{ fn }}"
    }
   ]
  },
  {
   "title": "Request Counts/ h",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cnt_request_count[1h])",
     "legendFormat": "{{ fn }}"
    }
   ]
  },
  {
   "title": "Differed Response / h",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cnt_differed_count[1h])",
     "legendFormat": "{{ fn }}"
    }
   ]
  },
  {
   "title": "Success Requests / h",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cnt_succeess_count[1h])",
     "legendFormat": "{{ fn }}"
    }
   ]
  },
  {
   "title": "Timedout Requests / h",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cnt_timeout_count[1h])",
     "legendFormat": "{{ fn }}"
    }
   ]
  },
  {
   "title": "Error Counters",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rate(cnt_error_count[10s])", "legendFormat": "Error" },
    {
     "expr": "rate(cnt_disconnect_count[10s])",
     "legendFormat": "Disconnect"
    },
    {
     "expr": "rate(cnt_file_error_count[10s])",
     "legendFormat": "File Error"
    }
   ]
  },
  {
   "title": "Scenario Counters",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cnt_failed_scenario_count[10s])",
     "legendFormat": "Failed Scenario"
    },
    {
     "expr": "rate(cnt_succeed_scenario_count[10s])",
     "legendFormat": "Succeed Scenario"
    }
   ]
  },
  { "title": "Histograms [ Error ]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "File Upload Latency [ERR]",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(hist_file_latency_bucket[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Success Latency [ERR]",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(hist_success_latency_bucket[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Timeout Latency [ERR]",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(hist_timeout_latency_bucket[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Differed Response Latency [ERR]",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(hist_differed_latency_bucket[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}