// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-05-02 21:25:27.889119 +0300 +03 m=+0.050406722
package domain

var (
	GitVersion = "334c1808a745d905209b2bdf00fa539ef6dc94df"
	SDKVersion = "v1.3.0"
)
