// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-04-30 09:28:37.973897 +0300 +03 m=+0.047474573
package domain

var (
	GitVersion = "9bb0979cc3852c31568e79b44f3886890d27e80a"
	SDKVersion = "v1.3.0"
)
