// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-05-01 10:50:33.76974 +0300 +03 m=+0.036448864
package domain

var (
	GitVersion = "ce54a348936dd465f50a6ee2daee9d4befae9e98"
	SDKVersion = "v1.3.0"
)
